import { chmod, mkdir, stat, writeFile } from 'fs/promises'
import { dirname, join, resolve } from 'path'
import {
  resolvePersonaPlexLauncherPath,
  resolvePersonaPlexRuntimeStatePath,
  resolvePersonaPlexStationRoot,
} from './personaplex-probe.js'

export type PersonaPlexLauncherBootstrapOptions = {
  json: boolean
  dryRun: boolean
  force: boolean
  root?: string | null
  stationRoot?: string | null
  launcherPath?: string | null
  runtimeStatePath?: string | null
  runtimeUrl?: string | null
}

export type PersonaPlexLauncherBootstrapReceipt = {
  status: 'ready' | 'created' | 'would_create'
  generatedAt: string
  dryRun: boolean
  force: boolean
  stationRoot: string
  launcherPath: string
  runtimeScriptPath: string
  runtimeStatePath: string
  runtimeUrl: string
  created: string[]
  overwritten: string[]
  skipped: string[]
  nextActions: string[]
}

const DEFAULT_PERSONAPLEX_RUNTIME_URL = 'http://127.0.0.1:8998'
const RUNTIME_SCRIPT_NAME = 'start-personaplex-wsl.sh'
const GENERATED_BY = 'Generated by OpenJaws PersonaPlex launcher bootstrap.'

function trimToNull(value: string | null | undefined): string | null {
  return value?.trim() || null
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function powershellQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function validateRuntimeUrl(value: string): void {
  let parsed: URL
  try {
    parsed = new URL(value)
  } catch (error) {
    throw new Error(
      `Invalid PersonaPlex runtime URL: ${
        error instanceof Error ? error.message : String(error)
      }`,
    )
  }
  if (!['http:', 'https:'].includes(parsed.protocol)) {
    throw new Error(
      `PersonaPlex bootstrap runtime URL must use http or https, received ${parsed.protocol}`,
    )
  }
  if (parsed.username || parsed.password) {
    throw new Error('PersonaPlex bootstrap runtime URL must not include credentials.')
  }
}

export function parsePersonaPlexLauncherBootstrapArgs(
  argv: string[],
): PersonaPlexLauncherBootstrapOptions {
  const options: PersonaPlexLauncherBootstrapOptions = {
    json: false,
    dryRun: false,
    force: false,
    root: null,
    stationRoot:
      trimToNull(process.env.PERSONAPLEX_STATION_ROOT) ??
      trimToNull(process.env.OPENJAWS_LOCAL_COMMAND_STATION_ROOT),
    launcherPath: trimToNull(process.env.PERSONAPLEX_LAUNCHER_PATH),
    runtimeStatePath: trimToNull(process.env.PERSONAPLEX_RUNTIME_STATE_PATH),
    runtimeUrl:
      trimToNull(process.env.PERSONAPLEX_RUNTIME_URL) ??
      trimToNull(process.env.PERSONAPLEX_URL) ??
      DEFAULT_PERSONAPLEX_RUNTIME_URL,
  }

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    switch (arg) {
      case '--json':
        options.json = true
        break
      case '--dry-run':
      case '--check':
        options.dryRun = true
        break
      case '--force':
        options.force = true
        break
      case '--root':
        options.root = argv[index + 1]?.trim() || null
        index += 1
        break
      case '--station-root':
        options.stationRoot = argv[index + 1]?.trim() || null
        index += 1
        break
      case '--launcher-path':
        options.launcherPath = argv[index + 1]?.trim() || null
        index += 1
        break
      case '--runtime-state-path':
        options.runtimeStatePath = argv[index + 1]?.trim() || null
        index += 1
        break
      case '--runtime-url':
      case '--url':
        options.runtimeUrl = argv[index + 1]?.trim() || null
        index += 1
        break
      default:
        throw new Error(`Unknown argument: ${arg}`)
    }
  }

  return options
}

async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch {
    return false
  }
}

function buildPowerShellLauncherTemplate(args: {
  runtimeUrl: string
  runtimeScriptPath: string
  runtimeStatePath: string
}): string {
  return `# ${GENERATED_BY}
# This local file is ignored by git. Keep real credentials in environment variables.
param(
  [string]$RuntimeUrl = $(if ($env:PERSONAPLEX_RUNTIME_URL) { $env:PERSONAPLEX_RUNTIME_URL } else { ${powershellQuote(args.runtimeUrl)} }),
  [string]$WslScript = $(if ($env:PERSONAPLEX_WSL_SCRIPT) { $env:PERSONAPLEX_WSL_SCRIPT } else { ${powershellQuote(args.runtimeScriptPath)} })
)

$ErrorActionPreference = "Stop"
$StatePath = if ($env:PERSONAPLEX_RUNTIME_STATE_PATH) { $env:PERSONAPLEX_RUNTIME_STATE_PATH } else { ${powershellQuote(args.runtimeStatePath)} }
$StateDir = Split-Path -Parent $StatePath
New-Item -ItemType Directory -Path $StateDir -Force | Out-Null

function Write-PersonaPlexState {
  param([hashtable]$State)
  $State["updatedAt"] = (Get-Date).ToUniversalTime().ToString("o")
  $State | ConvertTo-Json -Depth 8 | Set-Content -Path $StatePath -Encoding UTF8
}

function Fail-PersonaPlexLaunch {
  param([string]$Status, [string]$Message)
  Write-PersonaPlexState @{
    status = $Status
    runtimeMode = "wsl"
    runtimeUrl = $RuntimeUrl
    failedAt = (Get-Date).ToUniversalTime().ToString("o")
    processId = $PID
    lastError = $Message
  }
  throw $Message
}

try {
  $ParsedRuntimeUrl = [Uri]$RuntimeUrl
} catch {
  Fail-PersonaPlexLaunch "invalid_runtime_url" "PERSONAPLEX_RUNTIME_URL is not a valid URL."
}

if ($ParsedRuntimeUrl.UserInfo) {
  Fail-PersonaPlexLaunch "invalid_runtime_url" "PERSONAPLEX_RUNTIME_URL must not include credentials."
}

$Wsl = Get-Command "wsl.exe" -ErrorAction SilentlyContinue
if (-not $Wsl) {
  Fail-PersonaPlexLaunch "missing_wsl" "wsl.exe was not found. Install WSL or set PERSONAPLEX_WSL_SCRIPT to another local launcher path."
}

if (-not (Test-Path -LiteralPath $WslScript)) {
  Fail-PersonaPlexLaunch "missing_runtime_script" "PersonaPlex WSL launcher was not found at $WslScript."
}

$ScriptText = Get-Content -LiteralPath $WslScript -Raw
if ($ScriptText -like "*PERSONAPLEX_RUNTIME_COMMAND is not set*" -and -not $env:PERSONAPLEX_RUNTIME_COMMAND) {
  Fail-PersonaPlexLaunch "runtime_command_required" "Set PERSONAPLEX_RUNTIME_COMMAND or replace the generated WSL script with the real local PersonaPlex runtime launcher."
}

Write-PersonaPlexState @{
  status = "launching"
  runtimeMode = "wsl"
  runtimeUrl = $RuntimeUrl
  protocol = $ParsedRuntimeUrl.Scheme
  host = $ParsedRuntimeUrl.Host
  port = if ($ParsedRuntimeUrl.Port -gt 0) { $ParsedRuntimeUrl.Port } else { 8998 }
  startedAt = (Get-Date).ToUniversalTime().ToString("o")
  processId = $PID
}

$ResolvedWslScript = (Resolve-Path -LiteralPath $WslScript).Path
$WslPath = (& wsl.exe wslpath -a $ResolvedWslScript).Trim()
if ($LASTEXITCODE -ne 0 -or -not $WslPath) {
  Fail-PersonaPlexLaunch "wsl_path_failed" "Could not convert $ResolvedWslScript to a WSL path."
}

$Process = Start-Process -FilePath "wsl.exe" -ArgumentList @("bash", $WslPath) -PassThru -WindowStyle Hidden
Write-PersonaPlexState @{
  status = "started"
  runtimeMode = "wsl"
  runtimeUrl = $RuntimeUrl
  protocol = $ParsedRuntimeUrl.Scheme
  host = $ParsedRuntimeUrl.Host
  port = if ($ParsedRuntimeUrl.Port -gt 0) { $ParsedRuntimeUrl.Port } else { 8998 }
  startedAt = (Get-Date).ToUniversalTime().ToString("o")
  processId = $PID
  wslPid = $Process.Id
}

Write-Host "PersonaPlex launcher started. Probe with: bun run personaplex:probe"
`
}

function buildWslLauncherTemplate(runtimeUrl: string): string {
  return `#!/usr/bin/env bash
# ${GENERATED_BY}
# Keep tokens in your shell environment. Do not write HF_TOKEN or other secrets into this file.
set -euo pipefail

if [[ -z "\${PERSONAPLEX_RUNTIME_URL:-}" ]]; then
  export PERSONAPLEX_RUNTIME_URL=${shellQuote(runtimeUrl)}
fi

if [[ -z "\${PERSONAPLEX_RUNTIME_COMMAND:-}" ]]; then
  cat >&2 <<'MESSAGE'
PERSONAPLEX_RUNTIME_COMMAND is not set.
Set it to the local Moshi/PersonaPlex server command, or replace this generated file with your real runtime launcher.
The runtime must answer the PersonaPlex chat WebSocket on PERSONAPLEX_RUNTIME_URL.
MESSAGE
  exit 2
fi

exec bash -lc "$PERSONAPLEX_RUNTIME_COMMAND"
`
}

async function writeGeneratedFile(args: {
  path: string
  content: string
  dryRun: boolean
  force: boolean
  executable?: boolean
}): Promise<'created' | 'overwritten' | 'skipped' | 'would_create'> {
  const exists = await fileExists(args.path)
  if (args.dryRun) {
    return exists && !args.force ? 'skipped' : 'would_create'
  }
  if (exists && !args.force) {
    return 'skipped'
  }

  await mkdir(dirname(args.path), { recursive: true })
  await writeFile(args.path, args.content, 'utf8')
  if (args.executable) {
    try {
      await chmod(args.path, 0o755)
    } catch {
      // Windows ignores POSIX execute bits; the script still runs through bash.
    }
  }
  return exists ? 'overwritten' : 'created'
}

export async function bootstrapPersonaPlexLauncher(
  options: PersonaPlexLauncherBootstrapOptions,
): Promise<PersonaPlexLauncherBootstrapReceipt> {
  const root = resolve(options.root ?? process.cwd())
  const stationRoot = resolvePersonaPlexStationRoot({
    root,
    stationRoot: options.stationRoot,
  })
  const launcherPath = resolvePersonaPlexLauncherPath({
    root,
    stationRoot,
    launcherPath: options.launcherPath,
  })
  const runtimeStatePath = resolvePersonaPlexRuntimeStatePath({
    root,
    stationRoot,
    runtimeStatePath: options.runtimeStatePath,
  })
  const runtimeScriptPath = join(
    stationRoot,
    'personaplex-runtime',
    RUNTIME_SCRIPT_NAME,
  )
  const runtimeUrl = options.runtimeUrl?.trim() || DEFAULT_PERSONAPLEX_RUNTIME_URL
  validateRuntimeUrl(runtimeUrl)

  const writes = [
    {
      path: launcherPath,
      content: buildPowerShellLauncherTemplate({
        runtimeUrl,
        runtimeScriptPath,
        runtimeStatePath,
      }),
      executable: false,
    },
    {
      path: runtimeScriptPath,
      content: buildWslLauncherTemplate(runtimeUrl),
      executable: true,
    },
  ]

  const created: string[] = []
  const overwritten: string[] = []
  const skipped: string[] = []

  for (const write of writes) {
    const result = await writeGeneratedFile({
      ...write,
      dryRun: options.dryRun,
      force: options.force,
    })
    if (result === 'created' || result === 'would_create') {
      created.push(write.path)
    } else if (result === 'overwritten') {
      overwritten.push(write.path)
    } else {
      skipped.push(write.path)
    }
  }

  const changed = created.length + overwritten.length
  const status = options.dryRun && changed > 0
    ? 'would_create'
    : changed > 0
      ? 'created'
      : 'ready'

  return {
    status,
    generatedAt: new Date().toISOString(),
    dryRun: options.dryRun,
    force: options.force,
    stationRoot,
    launcherPath,
    runtimeScriptPath,
    runtimeStatePath,
    runtimeUrl,
    created,
    overwritten,
    skipped,
    nextActions: [
      `Set PERSONAPLEX_RUNTIME_COMMAND to the local PersonaPlex/Moshi server command, or replace ${runtimeScriptPath} with the real local runtime launcher.`,
      `Start the bridge with pwsh -NoProfile -ExecutionPolicy Bypass -File ${launcherPath}.`,
      'Run bun run personaplex:probe to verify the WebSocket hello byte before calling voice ready.',
    ],
  }
}

async function main(argv = process.argv.slice(2)): Promise<number> {
  const options = parsePersonaPlexLauncherBootstrapArgs(argv)
  const receipt = await bootstrapPersonaPlexLauncher(options)
  if (options.json) {
    console.log(JSON.stringify(receipt, null, 2))
  } else {
    console.log(
      [
        `PersonaPlex local launcher bootstrap: ${receipt.status}`,
        `Launcher: ${receipt.launcherPath}`,
        `Runtime script: ${receipt.runtimeScriptPath}`,
        ...receipt.nextActions.map(action => `- ${action}`),
      ].join('\n'),
    )
  }
  return 0
}

if (import.meta.main) {
  try {
    process.exitCode = await main()
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  }
}
