import { describe, expect, test } from 'bun:test'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { buildPersonaPlexLauncherWarnings } from './personaplex-probe.ts'
import {
  bootstrapPersonaPlexLauncher,
  parsePersonaPlexLauncherBootstrapArgs,
} from './personaplex-launcher-bootstrap.ts'

function createRoot() {
  return mkdtempSync(join(tmpdir(), 'openjaws-personaplex-bootstrap-'))
}

describe('personaplex-launcher-bootstrap', () => {
  test('parses explicit bootstrap paths and safe defaults', () => {
    expect(
      parsePersonaPlexLauncherBootstrapArgs([
        '--json',
        '--dry-run',
        '--force',
        '--root',
        'D:\\openjaws\\OpenJaws',
        '--station-root',
        'D:\\openjaws\\OpenJaws\\local-command-station',
        '--launcher-path',
        'D:\\openjaws\\OpenJaws\\local-command-station\\start-personaplex-voice.ps1',
        '--runtime-state-path',
        'D:\\openjaws\\OpenJaws\\local-command-station\\personaplex-runtime\\runtime.json',
        '--runtime-url',
        'http://127.0.0.1:8998',
      ]),
    ).toMatchObject({
      json: true,
      dryRun: true,
      force: true,
      root: 'D:\\openjaws\\OpenJaws',
      stationRoot: 'D:\\openjaws\\OpenJaws\\local-command-station',
      launcherPath:
        'D:\\openjaws\\OpenJaws\\local-command-station\\start-personaplex-voice.ps1',
      runtimeStatePath:
        'D:\\openjaws\\OpenJaws\\local-command-station\\personaplex-runtime\\runtime.json',
      runtimeUrl: 'http://127.0.0.1:8998',
    })
  })

  test('dry run reports generated files without writing local operator state', async () => {
    const root = createRoot()
    const receipt = await bootstrapPersonaPlexLauncher({
      json: true,
      dryRun: true,
      force: false,
      root,
      runtimeUrl: 'http://127.0.0.1:8998',
    })

    expect(receipt.status).toBe('would_create')
    expect(receipt.created).toHaveLength(2)
    expect(existsSync(receipt.launcherPath)).toBe(false)
    expect(existsSync(receipt.runtimeScriptPath)).toBe(false)
  })

  test('generates a non-secret PowerShell launcher and WSL runtime handoff', async () => {
    const root = createRoot()
    const receipt = await bootstrapPersonaPlexLauncher({
      json: true,
      dryRun: false,
      force: false,
      root,
      runtimeUrl: 'http://127.0.0.1:8998',
    })

    expect(receipt.status).toBe('created')
    expect(receipt.created).toHaveLength(2)
    expect(existsSync(receipt.launcherPath)).toBe(true)
    expect(existsSync(receipt.runtimeScriptPath)).toBe(true)

    const launcher = readFileSync(receipt.launcherPath, 'utf8')
    const runtimeScript = readFileSync(receipt.runtimeScriptPath, 'utf8')
    expect(launcher).toContain('PERSONAPLEX_RUNTIME_COMMAND')
    expect(launcher).toContain('Write-PersonaPlexState')
    expect(launcher).toContain('@("bash", $WslPath, $RuntimeUrl)')
    expect(runtimeScript).toContain('PERSONAPLEX_RUNTIME_COMMAND is not set')
    expect(runtimeScript).toContain('export PERSONAPLEX_RUNTIME_URL="$1"')
    expect(`${launcher}\n${runtimeScript}`).not.toMatch(/hf_[A-Za-z0-9_]{12,}/)
    expect(
      buildPersonaPlexLauncherWarnings({
        stationRoot: receipt.stationRoot,
        launcherPath: receipt.launcherPath,
      }),
    ).toEqual([])
  })

  test('preserves existing local launcher files unless force is explicit', async () => {
    const root = createRoot()
    const stationRoot = join(root, 'local-command-station')
    const launcherPath = join(stationRoot, 'start-personaplex-voice.ps1')
    mkdirSync(stationRoot, { recursive: true })
    writeFileSync(launcherPath, '# custom local launcher\n', 'utf8')

    const preserved = await bootstrapPersonaPlexLauncher({
      json: true,
      dryRun: false,
      force: false,
      root,
      runtimeUrl: 'http://127.0.0.1:8998',
    })

    expect(preserved.skipped).toContain(launcherPath)
    expect(readFileSync(launcherPath, 'utf8')).toBe('# custom local launcher\n')

    const regenerated = await bootstrapPersonaPlexLauncher({
      json: true,
      dryRun: false,
      force: true,
      root,
      runtimeUrl: 'http://127.0.0.1:8998',
    })

    expect(regenerated.overwritten).toContain(launcherPath)
    expect(readFileSync(launcherPath, 'utf8')).toContain(
      'Generated by OpenJaws PersonaPlex launcher bootstrap.',
    )
  })

  test('rejects credentialed runtime URLs before writing launcher files', async () => {
    const root = createRoot()
    await expect(
      bootstrapPersonaPlexLauncher({
        json: true,
        dryRun: false,
        force: false,
        root,
        runtimeUrl: 'http://user:secret@127.0.0.1:8998',
      }),
    ).rejects.toThrow('must not include credentials')
  })
})
